name: task_manager_getx
description: "Ostad GetX assignment"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  jwt_decoder: ^2.0.1
  ionicons: ^0.2.2
  salomon_bottom_bar: ^3.3.2
  image_picker: ^1.1.2
  gap: ^3.0.1
  http: ^1.2.1
  awesome_snackbar_content: ^0.1.3
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  internet_connection_checker: ^1.0.0+1
  get: ^4.6.6
  widget_and_text_animator: ^1.1.5




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

